name: Cryptic Backend Sentry
on:
  push:
    branches:
      - master
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_URL: https://sentry.the-morpheus.de/
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: cryptic
      SENTRY_PROJECT: java-backend
      SENTRY_LOG_LEVEL: DEBUG
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup Env Development
        if: github.ref == 'refs/heads/experimental'
        env:
          SENTRY_DEPLOY_ENVIRONMENT: development
        run: echo development
      - name: Setup Env Production
        if: github.ref == 'refs/heads/master'
        env:
          SENTRY_DEPLOY_ENVIRONMENT: production
        run: echo production
      - name: Setup Sentry CLI
        run: curl -sL https://sentry.io/get-cli/ | bash
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run with Gradle
        run: ./gradlew linkSentry
